/*QUESTIONS on SUBQUERY*/
/*1.DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'*/
SELECT 	ENAME FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM DEPT
                WHERE DNAME LIKE '%S');
                
/*2.QUERY TO DISPLAY THE EMPLOYEE NAMES WHO IS HAVING 
MAXIMUM SALARY IN DEPT NAME "ACCOUNTING"   */
SELECT ENAME
FROM EMP
WHERE SAL IN(SELECT MAX(SAL)FROM EMP)
AND DEPTNO IN(SELECT DEPTNO
FROM DEPT
WHERE DNAME ='ACCOUNTING');   

/*3.QUERY TO DISPLAY THE DEPT NAME WHO IS HAVING HIGHEST COMMISSION*/
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
				 FROM EMP
                 WHERE COMM IN(SELECT MAX(COMM)FROM EMP));
                 
/*4.QUERY TO DISPLAY THE EMPLOYEE NAMES WHOSE 
DEPARTMENT NAME HAS 2ND CHARACTER AS 'O' */
SELECT ENAME 
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO
			   FROM DEPT
               WHERE DNAME LIKE '_O%');
               
/*5.QUERY TO DISPLAY ALL THE EMPLOYEES WHO’S 
DEPT NUMBER IS SAME AS SCOTT.*/
SELECT ENAME
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM DEPT
                WHERE ENAME ='SCOTT');
                
/*6.QUERY TO DISPLAY ALL THE EMPLOYEES IN 
'OPERATIONS AND ACCOUNTING' DEPT. */
SELECT ENAME
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO
                FROM DEPT
                WHERE DNAME IN('OPERATIONS','ACCOUNTING'));
                
/*7.LIST THE EMPLOYEES WHO HAS SALARY GREATER THAN MILLER*/
SELECT ENAME
FROM EMP 
WHERE SAL>(SELECT SAL
           FROM EMP
           WHERE ENAME ='MILLER');
           
/*8. LIST DEPARTMENT NAME HAVING ATLEAST 3 SALESMAN*/
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP
                WHERE JOB ='SALESMAN'
                GROUP BY DEPTNO
                HAVING COUNT(*)>=3);       
                
/*9.DISPLAY THE DNAME OF AN EMPLOYEES WHO HAS NO REPORTING MANAGER.*/
SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
              FROM EMP
              WHERE MGR IS NULL);
              
/*10.LIST ALL THE EMPLOYEES WHO ARE REPORTING TO JONES MANAGER */
SELECT ENAME
FROM EMP
WHERE MGR=(SELECT EMPNO
		   FROM EMP
           WHERE EMPNO=(SELECT MGR
                        FROM EMP
                        WHERE ENAME='JONES'));
                        
/*11.LIST EMPLOYEES FROM RESEARCH&ACCOUNTING HAVING ATLEAST 2 REPORTING. */
SELECT ENAME
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO
              FROM DEPT
              WHERE DNAME IN("RESEARCH","ACCOUNTING")
              GROUP BY DEPTNO
              HAVING COUNT(*)>=2);
              
/*12. DISPLAY THE DEPARTNAME OF THE EMPLOYEE WHOSE NAME DOES NOT STARTS 
WITH S AND SALARY BETWEEN 1500 TO 3000. */
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
              FROM EMP
              WHERE ENAME NOT LIKE "S%" AND SAL BETWEEN 1501 AND 2999);
              
/*13.DISPLAY LOCATION OF EMPLOYEE WHOSE SALARY IS MINIMUM 
SALARY BUT SALARY IS GREATER THAN 2000  */
SELECT LOC FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
              FROM EMP
              WHERE SAL IN(SELECT MIN(SAL)
                           FROM EMP)
						   AND SAL>2000);
                           
/*14.DISPLAY THE LOCATION OF AN EMPLOYEE IN ACCOUNTING DEPARTMENT. */
SELECT LOC
FROM DEPT
WHERE DNAME ="ACCOUNTING";

/*15.DISPLAY THE DEPARTMENT ‘S LOCATION THAT IS 
HAVING GREATER THAN FOUR EMPLOYEES IN IT.*/
SELECT LOC 
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
				FROM EMP
                GROUP BY DEPTNO
                HAVING COUNT(*)>4);
                
/*16.WRITE A QUERY TO DISPLAY ALL THE EMPLOYEE WHOSE JOB NOT 
SAME AS ALLEN AND SALARY IS GREATER THAN MARTIN. */
SELECT ENAME
FROM EMP
WHERE JOB IN(SELECT JOB
             FROM EMP
             WHERE ENAME NOT LIKE "ALLEN")
             AND SAL >(SELECT SAL
                         FROM EMP
                         WHERE ENAME ="MARTIN");
              
SELECT ENAME
 FROM EMP
 WHERE JOB !='ALLEN' AND SAL>(SELECT SAL
 FROM EMP
 WHERE ENAME ='MARTIN');

/*17.DISPLAY ALL THE EMPLOYEES WHO IS HAVING LOCATION IS SAME AS ADAM'S MANAGER? */
 SELECT ENAME
 FROM EMP
 WHERE DEPTNO IN(SELECT DEPTNO
 FROM DEPT
 WHERE LOC IN(SELECT LOC
 FROM DEPT
 WHERE DEPTNO IN(SELECT DEPTNO
 FROM EMP
 WHERE EMPNO IN(SELECT MGR
 FROM EMP
 WHERE ENAME='ADAM'))));
 
 /*18.DISPLAY THE JOB, MANAGER NUMBER OF EMPLOYEES WHO IS WORKING FOR JONES?*/
 SELECT JOB,MGR,COUNT(*) AS NO_OF_EMP
 FROM EMP 
 WHERE MGR=(SELECT EMPNO
            FROM EMP
            WHERE ENAME='JONES')
            GROUP BY JOB,MGR;
            
/*19.DISPLAY THE EMPLOYEE NAMES, HIGHER DATE, COMMISSION OF FORD'S MANAGER? */
SELECT ENAME,HIREDATE,COMM
FROM EMP
WHERE EMPNO IN(SELECT MGR
           FROM EMP
           WHERE ENAME='FORD');
           
/*20.DISPLAY THE NUMBER OF EMPLOYEES WHO ARE GETTING 
SALARY LESS THAN THE BLAKE'S MANAGER */
SELECT COUNT(*)
FROM EMP
WHERE SAL<(SELECT SAL
		   FROM EMP 
           WHERE EMPNO IN(SELECT MGR
		                  FROM EMP
                          WHERE ENAME='BLAKE'));
                          
/*21.LIST EMPLOYEES WHO LOCATED IN CHICAGO AND THEIR COMMISSION IS ZERO.*/
SELECT ENAME
FROM EMP
WHERE COMM IS NOT NULL AND DEPTNO IN(SELECT DEPTNO
                                      FROM DEPT
                                      WHERE LOC ='CHICAGO');  
                                      
/*22.LIST EMPLOYEES WHO WORK FOR SALES DEPARTMENT AND THEIR SALARY 
GREATER THAN AVERAGE SALARY OF THEIR DEPARTMENT. */                                     
SELECT ENAME
FROM EMP 
WHERE SAL>(SELECT AVG(SAL)
		   FROM EMP)AND DEPTNO IN(SELECT DEPTNO
                                  FROM DEPT
                                  WHERE DNAME='SALES');
                                  
/*23.LIST EMPLOYEES WHO ARE WORKING IN RESEARCH DEPARTMENT AND THEY ARE MANAGER.  */
SELECT ENAME 
FROM EMP 
WHERE JOB ='MANAGER' AND DEPTNO IN(SELECT DEPTNO
                                   FROM DEPT
                                   WHERE DNAME ='RESEARCH');
                                   
/*24.DISPLAY DEPARTMENT NAME OF THE EMPLOYEES WHO EARN COMMISSION. */
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP
                WHERE COMM IS NOT NULL);
                
/*25.DISPLAY DEPARTMENT NAME OF THE EMPLOYEE WHO EARN 
MAXIMUM SALARY AND HAVE NO REPORTING MANAGER */
SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
               FROM EMP 
               WHERE SAL=(SELECT MAX(SAL)
						  FROM EMP)
                          AND MGR IS NULL);
                          
/*26.DISPLAY EMPLOYEE DETAILS WHO ARE REPORTING TO BLAKE 
AND HAVE COMMISSION WITHOUT USING NULL OR NOT NULL */
SELECT *
FROM EMP
WHERE MGR IN(SELECT EMPNO
             FROM EMP
             WHERE ENAME ='BLAKE' AND COMM>0);  
             
/*27.LIST ALL THE DEPTNAME AND LOC OF ALL THE SALESMAN MANAGER-MANAGER'S */
SELECT DNAME,LOC
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP
                WHERE EMPNO IN(SELECT MGR
                               FROM EMP
                               WHERE JOB ='SALESMAN'));   
                               
/*28. LIST THE EMPLOYEE DEPTNAME AND LOC OF ALL THE EMPLOYEES WHO ARE CLERK
,REPORTING TO BLAKE AND SALARY IS LESSER THAN MARTIN SALARY */
SELECT DNAME ,LOC 
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP
                WHERE JOB = 'CLERK' AND MGR IN(SELECT EMPNO
											   FROM EMP
                                               WHERE ENAME ='BLAKE')AND SAL<(SELECT SAL
																			 FROM EMP
                                                                             WHERE ENAME ='MARTIN'));
                                                                             
/*29. LIST THE EMPLOYEES WHO DOES NOT DIRECTLY REPORT TO PRESIDENT,HAVE COMMISSION AND 
SALARY MORE THAN MAX SALARY OF ALL THE CLERK WITHOUT USING NULL OR NOT NULL  */
SELECT ENAME
FROM EMP 
WHERE MGR <>(SELECT EMPNO
             FROM EMP
             WHERE JOB='PRESIDENT')
             AND IFNULL(COMM,0)>0
             AND SAL>(SELECT MAX(SAL)
                      FROM EMP 
                      WHERE JOB='CLERK');
                      
/*30.LIST THE EMPLOYEES WHO JOINED AFTER 2 YEARS OF FIRST 
EMPLOYEE OF THE COMPANY AND MORE THAN BLAKE SALARY */
SELECT ENAME
FROM EMP
WHERE HIREDATE >(SELECT MIN(HIREDATE)+ INTERVAL '2' YEAR
				 FROM EMP)AND SAL>(SELECT SAL
                                    FROM EMP
                                    WHERE ENAME ='BLAKE'); 
                                    
/*31.DISPLAY LOCATION OF ALL THE EMPLOYEES WHO REPORTING TO BLAKE */
SELECT LOC 
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
              FROM EMP 
              WHERE MGR IN(SELECT EMPNO
                           FROM EMP
                           WHERE ENAME ='BLAKE'));
                           
/*32.LIST ALL THE EMPLOYEES WHOSE JOB IS SAME AS 
JONES AND THEIR SALARY LESSER THAN SCOTT */
SELECT ENAME
FROM EMP
WHERE JOB IN(SELECT JOB 
             FROM EMP 
             WHERE ENAME='JONES')AND SAL<(SELECT SAL 
                                        FROM EMP 
                                        WHERE ENAME='SCOTT');
                                        
/*33.DISPLAY ALL THE EMPLOYEES OF DEPARTMENT 30, 20 WITH THERE ANUAL 
SALARY AND HAVING ATLEAST 3 EMPLOYEES  */
SELECT ENAME,DEPTNO,SAL*12 AS ANNUAL_SAL
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO
				FROM EMP
                WHERE DEPTNO IN(20,30) 
                GROUP BY DEPTNO
                HAVING COUNT(*)>=3)
                ORDER BY DEPTNO; 
                
/*34.DISPLAY ALL THE EMPLOYEES WHO ARE EARN LESS THAN ANY OF THE SALESMAN?*/
SELECT ENAME
FROM EMP
WHERE SAL< ANY(SELECT SAL
FROM EMP
WHERE JOB ='SALESMAN');   

/*35.DISPLAY ALL THE EMPLOYEES WHO ARE JOINED BEFORE THE LAST PERSON?*/
SELECT * FROM EMP
WHERE HIREDATE<(SELECT MAX(HIREDATE) 
				FROM EMP);
                
/*36.FIND 3RD MINIMUM SALARY IN THE EMPLOYEE TABLE.*/
SELECT MIN(SAL)
FROM emp
WHERE SAL>(SELECT MIN(SAL)
           FROM emp
           WHERE SAL>(SELECT MIN(SAL)
                      FROM EMP));
                      
/*37.DISPLAY ALL THE EMPLOYEES WHO ARE EARNING MORE THAN ANY OF THE MANAGER. */
SELECT ENAME
FROM EMP
WHERE SAL>ANY(SELECT SAL
		   FROM EMP
           WHERE JOB ='MANAGER');
           
/*38.LIST EMPLOYEES WHO JOINED AFTER 4 YEARS OF 1ST EMPLOYEE 
OF THE COMPANY AND LESS THAN BLAKE SALARY.  */
SELECT ENAME
FROM EMP
WHERE HIREDATE IN(SELECT MIN(HIREDATE)+4*365
                  FROM EMP)AND SAL<(SELECT SAL
                                    FROM EMP
                                    WHERE ENAME ='BLAKE');   
                                    
/*39.DISPLAY THE DEPARTMENT INFORMATION OF 
EMPLOYEE WHO IS WORKING FOR NEW YORK LOCATION    */
SELECT DEPTNO
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO
FROM DEPT
WHERE LOC ='NEWYORK');   

/*40.DISPLAY LOCATION OF EMPLOYEES, WHOSE NAME DOESN'T 
START WITH A AND SALARY BETWEEN 1000 AND 3000.*/
SELECT LOC 
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP
                WHERE ENAME NOT LIKE 'A%' AND SAL BETWEEN 1001 AND 2999);
                
/*41.DISPLAY DEPARTMENT NAME OF ALL THE EMPLOYEES WHO ARE REPORTING TO BLAKE. */
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP
                WHERE MGR IN(SELECT EMPNO
						     FROM EMP
                             WHERE ENAME ='BLAKE'));
                             
/*42.DISPLAY THE MANAGER NUMBER,JOB AND DEPARTMENT NUMBER FOR THOSE 
WHO DON'T HAVE COMMISSION IN THE LOCATION CHICAGO OR DALLAS  */
SELECT MGR,JOB,DEPTNO
FROM EMP
WHERE COMM IS NULL AND DEPTNO IN(SELECT DEPTNO
FROM DEPT
WHERE LOC IN('CHICAGO','DALLAS'));

/*43.DISPLAY THE EMPLOYEE DETAILS WITH THEIR ANNUAL SALARY WHO EARN MAXIMUM COMMISSION */
SELECT EMP.* ,SAL*12 AS ANNUAL_SAL
FROM EMP
WHERE COMM IN(SELECT MAX(COMM)
              FROM EMP);
              
/*44.DISPLAY ALL THE EMPLOYEE WHOSE DEPARTMENT IS SALES AND WHO IS EARNING SOME COMMISSION 
(I.E COMMISSION IS NOT NULL OR ZERO)AND WHO IS HIRED BEFORE THE LAST PERSON HIRED.  */
SELECT ENAME
FROM EMP
WHERE COMM>0 AND HIREDATE<(SELECT MAX(HIREDATE)
                           FROM EMP)AND DEPTNO IN(SELECT DEPTNO
                                                  FROM DEPT
                                                  WHERE DNAME ='SALES');
                                                  
/*45.DISPLAY ALL THE DEPARTMENT NAMES FOR WARD'S MANAGER'S MANAGER */
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP
                WHERE EMPNO IN(SELECT MGR
                               FROM EMP
                                WHERE EMPNO IN(SELECT MGR
											   FROM EMP
                                               WHERE ENAME ='WARD')));
                                               
/*46:DISPLAY DEPARTMENT NAMES OF EMPLOYEE'S WHOSE SALARY IS 
GREATER THAN AVERAGE SALARY OF ALL THE CLERK'S     */
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM EMP 
                WHERE SAL>ALL(SELECT AVG(SAL)
                           FROM EMP
                           WHERE JOB='CLERK'));
                           
/*47.DISPLAY THE LAST EMPLOYEE RECORD WITH 25% HIKE IN SALARY.*/
SELECT *
FROM EMP
WHERE HIREDATE IN(SELECT MAX(HIREDATE)
				  FROM EMP)AND SAL IN(SELECT SAL+SAL*0.25
                                      FROM EMP);      
                                      
/*48.DISPLAY THE DEPARTMENT NUMBER WHO WORKING IN SALES DEPARTMENT AND THEY ARE MANAGER.*/
SELECT DEPTNO
FROM EMP
WHERE JOB ='MANAGER'AND DEPTNO IN(SELECT DEPTNO
                                   FROM DEPT
                                   WHERE DNAME= 'SALES');  
                                   
/*49.DISPLAY DEPARTMENT NAME OF THE EMPLOYEE WHO EARN MINMUM SALARY AND HAVE REPORTING MANAGER */
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
				FROM EMP
                WHERE SAL IN( SELECT MAX(SAL)
                             FROM EMP)
                              AND MGR IS NOT NULL);
                              
/*50.DISPLAY HIREDATE AND JOB OF ALL THE EMPLOYEES WORKING FOR SALES */
SELECT HIREDATE,SAL
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO
				FROM DEPT
				WHERE DNAME='SALES') ;                             

                        
	
                 